//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.Common.ServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.IConfigurationService")]
    public interface IConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/IsInitialized", ReplyAction="http://tempuri.org/IConfigurationService/IsInitializedResponse")]
        bool IsInitialized();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/IsInitialized", ReplyAction="http://tempuri.org/IConfigurationService/IsInitializedResponse")]
        System.Threading.Tasks.Task<bool> IsInitializedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetValue", ReplyAction="http://tempuri.org/IConfigurationService/GetValueResponse")]
        string GetValue(string section, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetValue", ReplyAction="http://tempuri.org/IConfigurationService/GetValueResponse")]
        System.Threading.Tasks.Task<string> GetValueAsync(string section, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetValues", ReplyAction="http://tempuri.org/IConfigurationService/GetValuesResponse")]
        string[] GetValues(string section, string partialKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetValues", ReplyAction="http://tempuri.org/IConfigurationService/GetValuesResponse")]
        System.Threading.Tasks.Task<string[]> GetValuesAsync(string section, string partialKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SetValue", ReplyAction="http://tempuri.org/IConfigurationService/SetValueResponse")]
        bool SetValue(string section, string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SetValue", ReplyAction="http://tempuri.org/IConfigurationService/SetValueResponse")]
        System.Threading.Tasks.Task<bool> SetValueAsync(string section, string key, string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationServiceChannel : ADS.Common.ServiceReferences.IConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<ADS.Common.ServiceReferences.IConfigurationService>, ADS.Common.ServiceReferences.IConfigurationService {
        
        public ConfigurationServiceClient() {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsInitialized() {
            return base.Channel.IsInitialized();
        }
        
        public System.Threading.Tasks.Task<bool> IsInitializedAsync() {
            return base.Channel.IsInitializedAsync();
        }
        
        public string GetValue(string section, string key) {
            return base.Channel.GetValue(section, key);
        }
        
        public System.Threading.Tasks.Task<string> GetValueAsync(string section, string key) {
            return base.Channel.GetValueAsync(section, key);
        }
        
        public string[] GetValues(string section, string partialKey) {
            return base.Channel.GetValues(section, partialKey);
        }
        
        public System.Threading.Tasks.Task<string[]> GetValuesAsync(string section, string partialKey) {
            return base.Channel.GetValuesAsync(section, partialKey);
        }
        
        public bool SetValue(string section, string key, string value) {
            return base.Channel.SetValue(section, key, value);
        }
        
        public System.Threading.Tasks.Task<bool> SetValueAsync(string section, string key, string value) {
            return base.Channel.SetValueAsync(section, key, value);
        }
    }
}
