
//Config Region 
export const FETCH_CONFIG_REQUEST='FETCH_CONFIG_REQUEST'
export const FETCH_CONFIG_SUCCESS='FETCH_CONFIG_SUCCESS'
export const FETCH_CONFIG_FAILUR='FETCH_CONFIG_FAILUR'
export const SEARCH_CONFIG_RESULT='SEARCH_CONFIG_RESULT'
export const PAGINATION_VALUE='PAGINATION_VALUE'

//////////////////////
