//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCore.Services.Security.Core.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecurityValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCore.Services.Security.Core.Localization.Resources.SecurityValidationResource", typeof(SecurityValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Actor Code] is not valid..
        /// </summary>
        internal static string Error_Actor_Code_Empty {
            get {
                return ResourceManager.GetString("Error_Actor_Code_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Actor] with the same name or code is already exists..
        /// </summary>
        internal static string Error_Actor_Duplicate {
            get {
                return ResourceManager.GetString("Error_Actor_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Actor] cannot not to be empty.
        /// </summary>
        internal static string Error_Actor_Empty {
            get {
                return ResourceManager.GetString("Error_Actor_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App Id] Cannot Delete This Actor.
        /// </summary>
        internal static string Error_Actor_Exists {
            get {
                return ResourceManager.GetString("Error_Actor_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Actor] is not valid..
        /// </summary>
        internal static string Error_Actor_Id {
            get {
                return ResourceManager.GetString("Error_Actor_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Actor Id] cannot be empty..
        /// </summary>
        internal static string Error_Actor_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Actor_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Actor Id] cannot have a value..
        /// </summary>
        internal static string Error_Actor_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Actor_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Actor Id] Should be exists..
        /// </summary>
        internal static string Error_Actor_NotExists {
            get {
                return ResourceManager.GetString("Error_Actor_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App Code] is not valid..
        /// </summary>
        internal static string Error_App_Code_Empty {
            get {
                return ResourceManager.GetString("Error_App_Code_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App] with the same attributes already exists..
        /// </summary>
        internal static string Error_App_Duplicate {
            get {
                return ResourceManager.GetString("Error_App_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App] cannot be empty.
        /// </summary>
        internal static string Error_App_Empty {
            get {
                return ResourceManager.GetString("Error_App_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App] is not valid..
        /// </summary>
        internal static string Error_App_Id {
            get {
                return ResourceManager.GetString("Error_App_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App Id] cannot be empty..
        /// </summary>
        internal static string Error_App_Id_Empty {
            get {
                return ResourceManager.GetString("Error_App_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App Id] cannot have a value..
        /// </summary>
        internal static string Error_App_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_App_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App] Could not be found..
        /// </summary>
        internal static string Error_App_NotExists {
            get {
                return ResourceManager.GetString("Error_App_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App] cannot be deleted due to existing active relations..
        /// </summary>
        internal static string Error_App_Relations_Exist {
            get {
                return ResourceManager.GetString("Error_App_Relations_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim Code] is not valid..
        /// </summary>
        internal static string Error_Claim_Code_Empty {
            get {
                return ResourceManager.GetString("Error_Claim_Code_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim] with the same name or code is already exists..
        /// </summary>
        internal static string Error_Claim_Duplicate {
            get {
                return ResourceManager.GetString("Error_Claim_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim] cannot not to be empty.
        /// </summary>
        internal static string Error_Claim_Empty {
            get {
                return ResourceManager.GetString("Error_Claim_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim Id] Cannot Delete This Actor.
        /// </summary>
        internal static string Error_Claim_Exists {
            get {
                return ResourceManager.GetString("Error_Claim_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim] is not valid..
        /// </summary>
        internal static string Error_Claim_Id {
            get {
                return ResourceManager.GetString("Error_Claim_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim Id] cannot be empty..
        /// </summary>
        internal static string Error_Claim_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Claim_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim Id] cannot have a value..
        /// </summary>
        internal static string Error_Claim_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Claim_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Claim Id] Should be exists..
        /// </summary>
        internal static string Error_Claim_NotExists {
            get {
                return ResourceManager.GetString("Error_Claim_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Role Code] is not valid..
        /// </summary>
        internal static string Error_Role_Code_Empty {
            get {
                return ResourceManager.GetString("Error_Role_Code_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Role] with the same name or code is already exists..
        /// </summary>
        internal static string Error_Role_Duplicate {
            get {
                return ResourceManager.GetString("Error_Role_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Role] cannot not to be empty.
        /// </summary>
        internal static string Error_Role_Empty {
            get {
                return ResourceManager.GetString("Error_Role_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security App Id] Cannot Delete This Role.
        /// </summary>
        internal static string Error_Role_Exists {
            get {
                return ResourceManager.GetString("Error_Role_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Role] is not valid..
        /// </summary>
        internal static string Error_Role_Id {
            get {
                return ResourceManager.GetString("Error_Role_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Role Id] cannot be empty..
        /// </summary>
        internal static string Error_Role_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Role_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Role Id] cannot have a value..
        /// </summary>
        internal static string Error_Role_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Role_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Security Role Id] Should be exists..
        /// </summary>
        internal static string Error_Role_NotExists {
            get {
                return ResourceManager.GetString("Error_Role_NotExists", resourceCulture);
            }
        }
    }
}
