//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcs.Invoicing.Services.Config.Application.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mcs.Invoicing.Services.Config.Application.Common.Localization.ValidationResources" +
                            "", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config] is duplicate..
        /// </summary>
        internal static string CreateConfigItemCommand_Error_Duplicate {
            get {
                return ResourceManager.GetString("CreateConfigItemCommand_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config] is not valid..
        /// </summary>
        internal static string CreateConfigItemCommand_Error_Empty {
            get {
                return ResourceManager.GetString("CreateConfigItemCommand_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Key] is not valid..
        /// </summary>
        internal static string CreateConfigItemCommand_Error_Key {
            get {
                return ResourceManager.GetString("CreateConfigItemCommand_Error_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Module] is not valid..
        /// </summary>
        internal static string CreateConfigItemCommand_Error_Module {
            get {
                return ResourceManager.GetString("CreateConfigItemCommand_Error_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Value] is not valid..
        /// </summary>
        internal static string CreateConfigItemCommand_Error_Value {
            get {
                return ResourceManager.GetString("CreateConfigItemCommand_Error_Value", resourceCulture);
            }
        }
    }
}
