#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Telerik.OpenAccess.Metadata.Relational;
using ADS.Tamam.Services.DataAcquisition.Models;

namespace ADS.Tamam.Services.DataAcquisition
{

	public partial class DataContextMetadataSource : FluentMetadataSource
	{
		
		protected override IList<MappingConfiguration> PrepareMapping()
		{
			List<MappingConfiguration> mappingConfigurations = new List<MappingConfiguration>();

            //var rawDataConfg = new MappingConfiguration<PullMechanismModel> ();
            //rawDataConfg.MapType ( p => new
            //{
            //    Id = p.Id ,
            //    PersonId = p.PersonId ,
            //    EventDate = p.EventDate ,
            //    TerminalId = p.TerminalId ,
            //    EventType = p.EventType
            //} ).UpdateSchema(false);

            //mappingConfigurations.Add ( rawDataConfg );
			return mappingConfigurations;
		}
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "DataContext";
			container.DefaultNamespace = "ADS.Tamam.Services.DataAcquisition";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
	}
}
#pragma warning restore 1591
