#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.Configuration;
using ADS.Tamam.Common.Data.ORM;

namespace ADS.Tamam.Services.DataAcquisition	
{
    public partial class DataContext : TamamBaseContext , IDataContextUnitOfWork  
	{
		private static string connectionStringName = @"ConectionString";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = new DataContextMetadataSource();
		
		public DataContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public DataContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public DataContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public DataContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public DataContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of DataContext.
		/// </summary>
		/// <param name="config">The BackendConfiguration of DataContext.</param>
        static void CustomizeBackendConfiguration( ref BackendConfiguration config )
        {
            config.SecondLevelCache.Enabled = false;
            config.Backend = ConfigurationManager.AppSettings["BackEnd"];
            config.ProviderName = ConfigurationManager.AppSettings["ProviderName"];
        }
		
	}
	
	public interface IDataContextUnitOfWork : IUnitOfWork
	{
	}
}
#pragma warning restore 1591
