//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCore.Services.Hiring.Core.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCore.Services.Hiring.Core.Localization.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advertisements  Advertisement] is not valid..
        /// </summary>
        internal static string Advertisement_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Advertisement_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advertisements Advertisement] with the same attributes already exists..
        /// </summary>
        internal static string Advertisement_Error_Duplicate {
            get {
                return ResourceManager.GetString("Advertisement_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advertisements  Advertisement] is not valid..
        /// </summary>
        internal static string Advertisement_Error_Empty {
            get {
                return ResourceManager.GetString("Advertisement_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advertisement] is not found..
        /// </summary>
        internal static string Advertisement_Error_NotExists {
            get {
                return ResourceManager.GetString("Advertisement_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Applications  Application] is not valid..
        /// </summary>
        internal static string Application_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Application_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Applications Application] with the same attributes already exists..
        /// </summary>
        internal static string Application_Error_Duplicate {
            get {
                return ResourceManager.GetString("Application_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Applications  Application] is not valid..
        /// </summary>
        internal static string Application_Error_Empty {
            get {
                return ResourceManager.GetString("Application_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Application] is not found..
        /// </summary>
        internal static string Application_Error_NotExists {
            get {
                return ResourceManager.GetString("Application_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Candidates  Candidate] is not valid..
        /// </summary>
        internal static string Candidate_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Candidate_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Candidates Candidate] with the same attributes already exists..
        /// </summary>
        internal static string Candidate_Error_Duplicate {
            get {
                return ResourceManager.GetString("Candidate_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Candidates  Candidate] is not valid..
        /// </summary>
        internal static string Candidate_Error_Empty {
            get {
                return ResourceManager.GetString("Candidate_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Candidate] is not found..
        /// </summary>
        internal static string Candidate_Error_NotExists {
            get {
                return ResourceManager.GetString("Candidate_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advertisements AdvertisementId] should not be empty..
        /// </summary>
        internal static string Error_Advertisement_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Advertisement_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Applications ApplicationId] should not be empty..
        /// </summary>
        internal static string Error_Application_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Application_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Candidates CandidateId] should not be empty..
        /// </summary>
        internal static string Error_Candidate_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Candidate_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HiringProcesses HiringProcessId] should not be empty..
        /// </summary>
        internal static string Error_HiringProcess_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_HiringProcess_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organizations OrganizationId] should not be empty..
        /// </summary>
        internal static string Error_Organization_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Organization_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Skills SkillId] should not be empty..
        /// </summary>
        internal static string Error_Skill_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Skill_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HiringProcesses  HiringProcess] is not valid..
        /// </summary>
        internal static string HiringProcess_Code_Error_Empty {
            get {
                return ResourceManager.GetString("HiringProcess_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HiringProcesses HiringProcess] with the same attributes already exists..
        /// </summary>
        internal static string HiringProcess_Error_Duplicate {
            get {
                return ResourceManager.GetString("HiringProcess_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HiringProcesses  HiringProcess] is not valid..
        /// </summary>
        internal static string HiringProcess_Error_Empty {
            get {
                return ResourceManager.GetString("HiringProcess_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HiringProcesses] is not found..
        /// </summary>
        internal static string HiringProcess_Error_NotExists {
            get {
                return ResourceManager.GetString("HiringProcess_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organizations  Organization] is not valid..
        /// </summary>
        internal static string Organization_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Organization_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organizations Organization] with the same attributes already exists..
        /// </summary>
        internal static string Organization_Error_Duplicate {
            get {
                return ResourceManager.GetString("Organization_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organizations  Organization] is not valid..
        /// </summary>
        internal static string Organization_Error_Empty {
            get {
                return ResourceManager.GetString("Organization_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organization] is not found..
        /// </summary>
        internal static string Organization_Error_NotExists {
            get {
                return ResourceManager.GetString("Organization_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Skills  Skill] is not valid..
        /// </summary>
        internal static string Skill_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Skill_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Skills Skill] with the same attributes already exists..
        /// </summary>
        internal static string Skill_Error_Duplicate {
            get {
                return ResourceManager.GetString("Skill_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Skills  Skill] is not valid..
        /// </summary>
        internal static string Skill_Error_Empty {
            get {
                return ResourceManager.GetString("Skill_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Skill] is not found..
        /// </summary>
        internal static string Skill_Error_NotExists {
            get {
                return ResourceManager.GetString("Skill_Error_NotExists", resourceCulture);
            }
        }
    }
}
