//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCore.Services.Notifications.Core.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationsValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationsValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCore.Services.Notifications.Core.Localization.Resources.NotificationsValidationR" +
                            "esource", typeof(NotificationsValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template Attachments] is not valid..
        /// </summary>
        internal static string Error_MessageTemplate_Attachment_Invalid {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_Attachment_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template Body] cannot be empty..
        /// </summary>
        internal static string Error_MessageTemplate_Body_Empty {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_Body_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template Code] code cannot be empty..
        /// </summary>
        internal static string Error_MessageTemplate_Code_Empty {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_Code_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template] with the same attributes already exists..
        /// </summary>
        internal static string Error_MessageTemplate_Duplicate {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template] cannot be empty..
        /// </summary>
        internal static string Error_MessageTemplate_Empty {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template Id] cannot have a value..
        /// </summary>
        internal static string Error_MessageTemplate_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template Key] is not valid..
        /// </summary>
        internal static string Error_MessageTemplate_Key_Invalid {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_Key_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message Template] could not be found..
        /// </summary>
        internal static string Error_MessageTemplate_NotExists {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ResolveRequest] messagetemplate isnot found.
        /// </summary>
        internal static string Error_MessageTemplate_NotFound {
            get {
                return ResourceManager.GetString("Error_MessageTemplate_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ResolveRequest] cannot be empty..
        /// </summary>
        internal static string Error_ResolveRequest_Empty {
            get {
                return ResourceManager.GetString("Error_ResolveRequest_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ResolveRequest] extrakeys.
        /// </summary>
        internal static string Error_ResolveRequest_ExtraKeys {
            get {
                return ResourceManager.GetString("Error_ResolveRequest_ExtraKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ResolveRequest Key] is not valid..
        /// </summary>
        internal static string Error_ResolveRequest_Key_Invalid {
            get {
                return ResourceManager.GetString("Error_ResolveRequest_Key_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ResolveRequest] messageTemplateId cannot be empty..
        /// </summary>
        internal static string Error_ResolveRequest_MessageTemplateId_Empty {
            get {
                return ResourceManager.GetString("Error_ResolveRequest_MessageTemplateId_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ResolveRequest] missingkeys.
        /// </summary>
        internal static string Error_ResolveRequest_MissingKeys {
            get {
                return ResourceManager.GetString("Error_ResolveRequest_MissingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ResolveRequest] requestId cannot be empty..
        /// </summary>
        internal static string Error_ResolveRequest_RequestId_Empty {
            get {
                return ResourceManager.GetString("Error_ResolveRequest_RequestId_Empty", resourceCulture);
            }
        }
    }
}
