//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.Tamam.Common.Data.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADS.Tamam.Common.Data.Culture.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Steps Sequance should be Unique.
        /// </summary>
        public static string ApprovalStepsUnique {
            get {
                return ResourceManager.GetString("ApprovalStepsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Code is already used in another one.
        /// </summary>
        public static string AttendanceCodeIsCodeUnique {
            get {
                return ResourceManager.GetString("AttendanceCodeIsCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code cannot be null or empty.
        /// </summary>
        public static string AttendanceCodeIsEmpty {
            get {
                return ResourceManager.GetString("AttendanceCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code should be unique.
        /// </summary>
        public static string DepartmentCodeUnique {
            get {
                return ResourceManager.GetString("DepartmentCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name (Culture Variant) is not provided.
        /// </summary>
        public static string DepartmentNameCultureVariantEmpty {
            get {
                return ResourceManager.GetString("DepartmentNameCultureVariantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name is not provided.
        /// </summary>
        public static string DepartmentNameEmpty {
            get {
                return ResourceManager.GetString("DepartmentNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name should be unique for every level.
        /// </summary>
        public static string DepartmentNameUnique {
            get {
                return ResourceManager.GetString("DepartmentNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Parent Can not be the department itself.
        /// </summary>
        public static string DepartmentParentEqSelf {
            get {
                return ResourceManager.GetString("DepartmentParentEqSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one Root department is allowed..
        /// </summary>
        public static string DepartmentParentInvalid {
            get {
                return ResourceManager.GetString("DepartmentParentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent department cant be a child of the same department.
        /// </summary>
        public static string DepartmentParentRecursive {
            get {
                return ResourceManager.GetString("DepartmentParentRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Cannot be deleted, It&apos;s being used in Department Rule Policy.
        /// </summary>
        public static string DepartmentUsedInPolicy {
            get {
                return ResourceManager.GetString("DepartmentUsedInPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse can not to be cancelled.
        /// </summary>
        public static string ExcuseCanCancelled {
            get {
                return ResourceManager.GetString("ExcuseCanCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse can not to be reviewed.
        /// </summary>
        public static string ExcuseCanReviewed {
            get {
                return ResourceManager.GetString("ExcuseCanReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse Date is not provided.
        /// </summary>
        public static string ExcuseDateEmpty {
            get {
                return ResourceManager.GetString("ExcuseDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts in this time frame.
        /// </summary>
        public static string ExcuseDurationEqualZero {
            get {
                return ResourceManager.GetString("ExcuseDurationEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse End Time is not provided.
        /// </summary>
        public static string ExcuseEndTimeEmpty {
            get {
                return ResourceManager.GetString("ExcuseEndTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse End Time must be greater than Start Time.
        /// </summary>
        public static string ExcuseInvalidEndTime {
            get {
                return ResourceManager.GetString("ExcuseInvalidEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse Person is not provided.
        /// </summary>
        public static string ExcusePersonEmpty {
            get {
                return ResourceManager.GetString("ExcusePersonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not request excuse for old dates.
        /// </summary>
        public static string ExcuseRequestOldDate {
            get {
                return ResourceManager.GetString("ExcuseRequestOldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse Start Time is not provided.
        /// </summary>
        public static string ExcuseStartTimeEmpty {
            get {
                return ResourceManager.GetString("ExcuseStartTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse Status is not provided.
        /// </summary>
        public static string ExcuseStatusEmpty {
            get {
                return ResourceManager.GetString("ExcuseStatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse time overlaps with another one.
        /// </summary>
        public static string ExcuseUnique {
            get {
                return ResourceManager.GetString("ExcuseUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Approval Policy.
        /// </summary>
        public static string InvalidApprovalPolicy {
            get {
                return ResourceManager.GetString("InvalidApprovalPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave status must be Pending or Planned.
        /// </summary>
        public static string InvalidCreateLeaveStatus {
            get {
                return ResourceManager.GetString("InvalidCreateLeaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates orders are invalid.
        /// </summary>
        public static string InvalidDatesOrder {
            get {
                return ResourceManager.GetString("InvalidDatesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address Format.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Valid Leave Amount.
        /// </summary>
        public static string InvalidLeavePolicyAmount {
            get {
                return ResourceManager.GetString("InvalidLeavePolicyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check the carry over / Max carry over values.
        /// </summary>
        public static string InvalidLeavePolicyCarryOver {
            get {
                return ResourceManager.GetString("InvalidLeavePolicyCarryOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check the Allow Requests / Days before values.
        /// </summary>
        public static string InvalidLeavePolicyRequest {
            get {
                return ResourceManager.GetString("InvalidLeavePolicyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Leave Type.
        /// </summary>
        public static string InvalidLeaveType {
            get {
                return ResourceManager.GetString("InvalidLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the selected persons have a schedule overlapping with this schedule.
        /// </summary>
        public static string InvalidSchedulePerson {
            get {
                return ResourceManager.GetString("InvalidSchedulePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave can not to be cancelled.
        /// </summary>
        public static string LeaveCanCancelled {
            get {
                return ResourceManager.GetString("LeaveCanCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave can not to be edited.
        /// </summary>
        public static string LeaveCanEdit {
            get {
                return ResourceManager.GetString("LeaveCanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave can not to be reviewed.
        /// </summary>
        public static string LeaveCanReviewed {
            get {
                return ResourceManager.GetString("LeaveCanReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No working days in this time frame.
        /// </summary>
        public static string LeaveEffectiveDaysEqualZero {
            get {
                return ResourceManager.GetString("LeaveEffectiveDaysEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave End Date is not provided.
        /// </summary>
        public static string LeaveEndDateEmpty {
            get {
                return ResourceManager.GetString("LeaveEndDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave End Date must be greater than or equal to Leave Start Date.
        /// </summary>
        public static string LeaveInvalidStartAndEndDate {
            get {
                return ResourceManager.GetString("LeaveInvalidStartAndEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Person is not provided.
        /// </summary>
        public static string LeavePersonIdEmpty {
            get {
                return ResourceManager.GetString("LeavePersonIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Person is not active.
        /// </summary>
        public static string LeavePersonNotActive {
            get {
                return ResourceManager.GetString("LeavePersonNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0} days before leave start date.
        /// </summary>
        public static string LeaveRequestDaysBefore {
            get {
                return ResourceManager.GetString("LeaveRequestDaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to request leave.
        /// </summary>
        public static string LeaveRequestNotAllowed {
            get {
                return ResourceManager.GetString("LeaveRequestNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not request leave for old dates.
        /// </summary>
        public static string LeaveRequestOldDate {
            get {
                return ResourceManager.GetString("LeaveRequestOldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Start Date is not provided.
        /// </summary>
        public static string LeaveStartDateEmpty {
            get {
                return ResourceManager.GetString("LeaveStartDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Start is before Leave credit effective date..
        /// </summary>
        public static string LeaveStartDateInvalid {
            get {
                return ResourceManager.GetString("LeaveStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Status is not provided.
        /// </summary>
        public static string LeaveStatusIdEmpty {
            get {
                return ResourceManager.GetString("LeaveStatusIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Credit available for this leave type.
        /// </summary>
        public static string LeaveTypeHasNoCredit {
            get {
                return ResourceManager.GetString("LeaveTypeHasNoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type is not provided.
        /// </summary>
        public static string LeaveTypeIdEmpty {
            get {
                return ResourceManager.GetString("LeaveTypeIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave dates overlaps with another one.
        /// </summary>
        public static string LeaveUnique {
            get {
                return ResourceManager.GetString("LeaveUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name culture variant is used before.
        /// </summary>
        public static string NameCultureVariantNotUnique {
            get {
                return ResourceManager.GetString("NameCultureVariantNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is used before.
        /// </summary>
        public static string NameNotUnique {
            get {
                return ResourceManager.GetString("NameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Code is not provided.
        /// </summary>
        public static string OrganizationDetailCodeEmpty {
            get {
                return ResourceManager.GetString("OrganizationDetailCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name is not provided.
        /// </summary>
        public static string OrganizationDetailNameEmpty {
            get {
                return ResourceManager.GetString("OrganizationDetailNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Code is not provided.
        /// </summary>
        public static string PersonCodeEmpty {
            get {
                return ResourceManager.GetString("PersonCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Code Should be Unique.
        /// </summary>
        public static string PersonCodeUnique {
            get {
                return ResourceManager.GetString("PersonCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Department is not provided.
        /// </summary>
        public static string PersonDepartmentEmpty {
            get {
                return ResourceManager.GetString("PersonDepartmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Id.
        /// </summary>
        public static string PersonInvalidUserId {
            get {
                return ResourceManager.GetString("PersonInvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Person Can not be deactiviated beacuse some one else is reporting to him.
        /// </summary>
        public static string PersonIsManager {
            get {
                return ResourceManager.GetString("PersonIsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date is not provided.
        /// </summary>
        public static string PersonJoinDateEmpty {
            get {
                return ResourceManager.GetString("PersonJoinDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name should be between 4 and 100 in Length.
        /// </summary>
        public static string PersonNameLength {
            get {
                return ResourceManager.GetString("PersonNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person SSN Should not Exceed 255.
        /// </summary>
        public static string PersonSSNLength {
            get {
                return ResourceManager.GetString("PersonSSNLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id already associated with another Person.
        /// </summary>
        public static string PersonUserIdIsUnique {
            get {
                return ResourceManager.GetString("PersonUserIdIsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name is not provided.
        /// </summary>
        public static string PersonUsernameEmpty {
            get {
                return ResourceManager.GetString("PersonUsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name should be unique.
        /// </summary>
        public static string PersonUsernameUnique {
            get {
                return ResourceManager.GetString("PersonUsernameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy is being associated with Policy Groups.
        /// </summary>
        public static string PolicyAssociationsCheck {
            get {
                return ResourceManager.GetString("PolicyAssociationsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Code is not provided.
        /// </summary>
        public static string PolicyCodeEmpty {
            get {
                return ResourceManager.GetString("PolicyCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Code Should be Unique.
        /// </summary>
        public static string PolicyCodeUnique {
            get {
                return ResourceManager.GetString("PolicyCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Group can not be Deleted, because it may be associated with personnel or departments or policies.
        /// </summary>
        public static string PolicyGroupHaveAssociations {
            get {
                return ResourceManager.GetString("PolicyGroupHaveAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name (Culture Variant) Should not Exceed 50.
        /// </summary>
        public static string PolicyNameCultureVariantLength {
            get {
                return ResourceManager.GetString("PolicyNameCultureVariantLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name (Culture Variant) Should be Unique.
        /// </summary>
        public static string PolicyNameCultureVariantUnique {
            get {
                return ResourceManager.GetString("PolicyNameCultureVariantUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name Should not Exceed 50.
        /// </summary>
        public static string PolicyNameLength {
            get {
                return ResourceManager.GetString("PolicyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name Should be Unique.
        /// </summary>
        public static string PolicyNameUnique {
            get {
                return ResourceManager.GetString("PolicyNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Type is Not Valid.
        /// </summary>
        public static string PolicyTypeNotValid {
            get {
                return ResourceManager.GetString("PolicyTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Values are not valid.
        /// </summary>
        public static string PolicyValuesCheck {
            get {
                return ResourceManager.GetString("PolicyValuesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template must have at least one detail with shift.
        /// </summary>
        public static string ScheduleTemplateNoDetails {
            get {
                return ResourceManager.GetString("ScheduleTemplateNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Id Should not Exceed 100.
        /// </summary>
        public static string SecurityIdLength {
            get {
                return ResourceManager.GetString("SecurityIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift can not be deleted or deactivated because it has been associated with a schedule template.
        /// </summary>
        public static string ShiftHaveTemplates {
            get {
                return ResourceManager.GetString("ShiftHaveTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the selected shifts overlap in times.
        /// </summary>
        public static string ShiftOverlap {
            get {
                return ResourceManager.GetString("ShiftOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift start cant be equal to shift end.
        /// </summary>
        public static string ShiftStartEqEnd {
            get {
                return ResourceManager.GetString("ShiftStartEqEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Supervisor Must be from the same department.
        /// </summary>
        public static string SupervisorNotVaild {
            get {
                return ResourceManager.GetString("SupervisorNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template can not be deleted or deactivated because it has been associated with a schedule.
        /// </summary>
        public static string TemplateHaveSchedule {
            get {
                return ResourceManager.GetString("TemplateHaveSchedule", resourceCulture);
            }
        }
    }
}
