apiVersion: v1
kind: Service
metadata:
  name: audit-message-processor
  labels:    
    app: audit-message-processor
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: audit-message-processor__ENV__
spec:
  type: LoadBalancer
  selector:
    app: audit-message-processor
  ports:
  - port: 80
    targetPort: 80