apiVersion: v1
kind: Service
metadata:
  name: audit-api
  labels:    
    app: audit-api
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: audit-api__ENV__ 
spec:
  type: LoadBalancer
  selector:
    app: audit-api
  ports:
  - port: 80
    targetPort: 80