apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-message-processor-appsettings
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "AuditDbConnection": "__DBCONNECTIONSTRING__"
        },
        "Serilog": {
            "Using": [],
            "MinimumLevel": {
                "Default": "Information",
                "Override": {
                    "Microsoft.AspNetCore": "Warning",
                    "System": "Warning",
                    "Microsoft.EntityFrameworkCore": "Warning"
                }
            },
            "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId", "WithExceptionDetails" ],
            "WriteTo": [
                { "Name": "Debug" },
                { "Name": "Console" },
                {
                    "Name": "Elasticsearch",
                  "Args": {
                    "nodeUris": "__ElasticSearchUri__",
                    "indexFormat": "mcs-invoicing-{0:yyyy.MM}",
                    "autoRegisterTemplate": true,
                    "autoRegisterTemplateVersion": "ESv6"

                  }
                }
            ]
        },
        "AllowedHosts": "*",
        "Async.Service": {
            "Transport": {
                "Uri": "rabbitmq://__SERVICEBUSHOSTURI__/",
                "CredentialsUsername": "__SERVICEBUSUSERNAME__",
                "CredentialsPassword": "__SERVICEBUSPASSWORD__"
            },
            "EndPointName": "Mcs.Invoicing.Audit"
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-message-processor
  labels:    
    app: audit-message-processor
spec:
  selector:
    matchLabels:
      app: audit-message-processor
  template:
    metadata:
      labels:
        app: audit-message-processor
    spec:
      containers:
      - name: audit-message-processor
        image: __ACR__/audit.message.processor:__BUILDID__
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: audit-message-processor-appsettings
