using System.Net.Http;
using System.Threading.Tasks;
using IdentityModel.Client;

namespace Mcs.Invoicing.Services.Config.Client.Sdk.Clients.Rest
{
    // note : if this is going to be generated by Swagger, we need to check how can we send the bearer token to it.
    public class ConfigRestClient
    {
        #region props.

        private string _endpoint { get; set; }

        #endregion
        #region cst.

        public ConfigRestClient(string endpoint)
        {
            _endpoint = endpoint?.TrimEnd('/');
        }

        #endregion

        #region publics.

        public async Task<bool?> IsHealthy(string jwtToken = null)
        {
            var endpoint = $"{this._endpoint}/api/v1.0/configurations/healthy";

            var apiClient = new HttpClient();
            if (!string.IsNullOrWhiteSpace(jwtToken))
            {
                apiClient.SetBearerToken(jwtToken);
            }

            var response = await apiClient.GetAsync(endpoint);
            var content = await response.Content.ReadAsStringAsync();
            return bool.TryParse(content, out bool responseBool) ? (bool?) responseBool : null;
        }

        #endregion
    }
}
