//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCore.Services.Configurations.Core.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCore.Services.Configurations.Core.Localization.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App Code] cannot be empty..
        /// </summary>
        internal static string App_Code_Error_Empty {
            get {
                return ResourceManager.GetString("App_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App] with the same attributes already exists..
        /// </summary>
        internal static string App_Error_Duplicate {
            get {
                return ResourceManager.GetString("App_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App] is not valid..
        /// </summary>
        internal static string App_Error_Empty {
            get {
                return ResourceManager.GetString("App_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App] is not found..
        /// </summary>
        internal static string App_Error_NotExists {
            get {
                return ResourceManager.GetString("App_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App] is not valid..
        /// </summary>
        internal static string App_Id_Error_Add {
            get {
                return ResourceManager.GetString("App_Id_Error_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string App_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("App_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Config Code] cannot be empty..
        /// </summary>
        internal static string Config_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Config_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Config ]with the same attributes already exists..
        /// </summary>
        internal static string Config_Error_Duplicate {
            get {
                return ResourceManager.GetString("Config_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Config] is not valid..
        /// </summary>
        internal static string Config_Error_Empty {
            get {
                return ResourceManager.GetString("Config_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config ConfigId]  is not found..
        /// </summary>
        internal static string Config_Error_NotExists {
            get {
                return ResourceManager.GetString("Config_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Config Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string Config_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("Config_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Key] is not valid..
        /// </summary>
        internal static string Config_Key_NotValid {
            get {
                return ResourceManager.GetString("Config_Key_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App Id] cannot be empty..
        /// </summary>
        internal static string Error_App_Id_Empty {
            get {
                return ResourceManager.GetString("Error_App_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config App Id] should be empty..
        /// </summary>
        internal static string Error_App_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_App_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Config Id] should be empty..
        /// </summary>
        internal static string Error_Config_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Config_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Id] cannot be empty in edit operations..
        /// </summary>
        internal static string Error_ConfigEdit_Id_Empty {
            get {
                return ResourceManager.GetString("Error_ConfigEdit_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Module  Id] cannot be empty in edit operations..
        /// </summary>
        internal static string Error_ModuleEdit_Id_Empty {
            get {
                return ResourceManager.GetString("Error_ModuleEdit_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Module Code] cannot be empty..
        /// </summary>
        internal static string Module_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Module_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Module ] with the same attributes already exists..
        /// </summary>
        internal static string Module_Error_Duplicate {
            get {
                return ResourceManager.GetString("Module_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Module ] is not valid..
        /// </summary>
        internal static string Module_Error_Empty {
            get {
                return ResourceManager.GetString("Module_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Module  Id]  is not found..
        /// </summary>
        internal static string Module_Error_NotExists {
            get {
                return ResourceManager.GetString("Module_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Module  Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string Module_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("Module_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
    }
}
