//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.Tamam.Resources.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Attendance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Attendance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADS.Tamam.Resources.Culture.Attendance", typeof(Attendance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غياب.
        /// </summary>
        public static string Absent_Ar {
            get {
                return ResourceManager.GetString("Absent_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string Absent_En {
            get {
                return ResourceManager.GetString("Absent_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come On Time.
        /// </summary>
        public static string ComeOnTime {
            get {
                return ResourceManager.GetString("ComeOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عطلة.
        /// </summary>
        public static string Holiday_Ar {
            get {
                return ResourceManager.GetString("Holiday_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday_En {
            get {
                return ResourceManager.GetString("Holiday_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازة.
        /// </summary>
        public static string Leave_Ar {
            get {
                return ResourceManager.GetString("Leave_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave_En {
            get {
                return ResourceManager.GetString("Leave_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Early.
        /// </summary>
        public static string LeftEarly {
            get {
                return ResourceManager.GetString("LeftEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Late.
        /// </summary>
        public static string LeftLate {
            get {
                return ResourceManager.GetString("LeftLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed Punches.
        /// </summary>
        public static string MissedPunches {
            get {
                return ResourceManager.GetString("MissedPunches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوم عمل.
        /// </summary>
        public static string NormalDay_Ar {
            get {
                return ResourceManager.GetString("NormalDay_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Day.
        /// </summary>
        public static string NormalDay_En {
            get {
                return ResourceManager.GetString("NormalDay_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSet.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازة.
        /// </summary>
        public static string OnLeave_Ar {
            get {
                return ResourceManager.GetString("OnLeave_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Leave.
        /// </summary>
        public static string OnLeave_En {
            get {
                return ResourceManager.GetString("OnLeave_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        public static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهاية الاسبوع.
        /// </summary>
        public static string Weekend_Ar {
            get {
                return ResourceManager.GetString("Weekend_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string Weekend_En {
            get {
                return ResourceManager.GetString("Weekend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Less.
        /// </summary>
        public static string WorkedLess {
            get {
                return ResourceManager.GetString("WorkedLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked More.
        /// </summary>
        public static string WorkedMore {
            get {
                return ResourceManager.GetString("WorkedMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل فى عطلة.
        /// </summary>
        public static string WorkOnHoliday_Ar {
            get {
                return ResourceManager.GetString("WorkOnHoliday_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work On Holiday.
        /// </summary>
        public static string WorkOnHoliday_En {
            get {
                return ResourceManager.GetString("WorkOnHoliday_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل فى اجازة.
        /// </summary>
        public static string WorkOnLeave_Ar {
            get {
                return ResourceManager.GetString("WorkOnLeave_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work On Leave.
        /// </summary>
        public static string WorkOnLeave_En {
            get {
                return ResourceManager.GetString("WorkOnLeave_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل فى نهاية الاسبوع.
        /// </summary>
        public static string WorkOnWeekend_Ar {
            get {
                return ResourceManager.GetString("WorkOnWeekend_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work On Weekend.
        /// </summary>
        public static string WorkOnWeekend_En {
            get {
                return ResourceManager.GetString("WorkOnWeekend_En", resourceCulture);
            }
        }
    }
}
