//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.Tamam.Resources.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADS.Tamam.Resources.Culture.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string Active_Ar {
            get {
                return ResourceManager.GetString("Active_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active_En {
            get {
                return ResourceManager.GetString("Active_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        public static string All_Ar {
            get {
                return ResourceManager.GetString("All_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All_En {
            get {
                return ResourceManager.GetString("All_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضر.
        /// </summary>
        public static string Attended_Ar {
            get {
                return ResourceManager.GetString("Attended_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended.
        /// </summary>
        public static string Attended_En {
            get {
                return ResourceManager.GetString("Attended_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string Away {
            get {
                return ResourceManager.GetString("Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور متأخر.
        /// </summary>
        public static string CameLate_Ar {
            get {
                return ResourceManager.GetString("CameLate_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Come.
        /// </summary>
        public static string CameLate_En {
            get {
                return ResourceManager.GetString("CameLate_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور فى الوقت المسموح.
        /// </summary>
        public static string ComeOnGrace_Ar {
            get {
                return ResourceManager.GetString("ComeOnGrace_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come On Grace.
        /// </summary>
        public static string ComeOnGrace_En {
            get {
                return ResourceManager.GetString("ComeOnGrace_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داخل العمل حاليا.
        /// </summary>
        public static string CurrentlyIn_Ar {
            get {
                return ResourceManager.GetString("CurrentlyIn_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently In.
        /// </summary>
        public static string CurrentlyIn_En {
            get {
                return ResourceManager.GetString("CurrentlyIn_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be Deleted..
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted Successfully.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور مبكر.
        /// </summary>
        public static string EarlyCome_Ar {
            get {
                return ResourceManager.GetString("EarlyCome_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Come.
        /// </summary>
        public static string EarlyCome_En {
            get {
                return ResourceManager.GetString("EarlyCome_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف مبكر.
        /// </summary>
        public static string EarlyLeave_Ar {
            get {
                return ResourceManager.GetString("EarlyLeave_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Leave.
        /// </summary>
        public static string EarlyLeave_En {
            get {
                return ResourceManager.GetString("EarlyLeave_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse.
        /// </summary>
        public static string Excuse {
            get {
                return ResourceManager.GetString("Excuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justified.
        /// </summary>
        public static string Justified {
            get {
                return ResourceManager.GetString("Justified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غياب للتأخير.
        /// </summary>
        public static string LateAbsent_Ar {
            get {
                return ResourceManager.GetString("LateAbsent_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Absent.
        /// </summary>
        public static string LateAbsent_En {
            get {
                return ResourceManager.GetString("LateAbsent_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج متأخر.
        /// </summary>
        public static string LateLeave_Ar {
            get {
                return ResourceManager.GetString("LateLeave_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Leave.
        /// </summary>
        public static string LateLeave_En {
            get {
                return ResourceManager.GetString("LateLeave_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غادر فى الوقت المسموح.
        /// </summary>
        public static string LeaveOnGrace_Ar {
            get {
                return ResourceManager.GetString("LeaveOnGrace_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave On Grace.
        /// </summary>
        public static string LeaveOnGrace_En {
            get {
                return ResourceManager.GetString("LeaveOnGrace_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Error.
        /// </summary>
        public static string LicenseError {
            get {
                return ResourceManager.GetString("LicenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول مفقود.
        /// </summary>
        public static string MissedInPunch_Ar {
            get {
                return ResourceManager.GetString("MissedInPunch_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed In Punch.
        /// </summary>
        public static string MissedInPunch_En {
            get {
                return ResourceManager.GetString("MissedInPunch_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج مفقود.
        /// </summary>
        public static string MissedOutPunch_Ar {
            get {
                return ResourceManager.GetString("MissedOutPunch_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed Out Punch.
        /// </summary>
        public static string MissedOutPunch_En {
            get {
                return ResourceManager.GetString("MissedOutPunch_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من حالات الحضور و الانصراف.
        /// </summary>
        public static string MultipleAttendanceStatuses_Ar {
            get {
                return ResourceManager.GetString("MultipleAttendanceStatuses_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Attendance Statuses.
        /// </summary>
        public static string MultipleAttendanceStatuses_En {
            get {
                return ResourceManager.GetString("MultipleAttendanceStatuses_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من الاقسام.
        /// </summary>
        public static string MultipleDepartments_Ar {
            get {
                return ResourceManager.GetString("MultipleDepartments_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Departments.
        /// </summary>
        public static string MultipleDepartments_En {
            get {
                return ResourceManager.GetString("MultipleDepartments_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من انواع التوظيف.
        /// </summary>
        public static string MultipleEmploymentTypes_Ar {
            get {
                return ResourceManager.GetString("MultipleEmploymentTypes_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Employment Types.
        /// </summary>
        public static string MultipleEmploymentTypes_En {
            get {
                return ResourceManager.GetString("MultipleEmploymentTypes_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من الاجناس.
        /// </summary>
        public static string MultipleGenders_Ar {
            get {
                return ResourceManager.GetString("MultipleGenders_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Genders.
        /// </summary>
        public static string MultipleGenders_En {
            get {
                return ResourceManager.GetString("MultipleGenders_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من المسميات الوظيفية.
        /// </summary>
        public static string MultipleJobTitles_Ar {
            get {
                return ResourceManager.GetString("MultipleJobTitles_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Job Titles.
        /// </summary>
        public static string MultipleJobTitles_En {
            get {
                return ResourceManager.GetString("MultipleJobTitles_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من الموظفين.
        /// </summary>
        public static string MultiplePersonnel_Ar {
            get {
                return ResourceManager.GetString("MultiplePersonnel_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Personnel.
        /// </summary>
        public static string MultiplePersonnel_En {
            get {
                return ResourceManager.GetString("MultiplePersonnel_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من الورديات.
        /// </summary>
        public static string MultipleShifts_Ar {
            get {
                return ResourceManager.GetString("MultipleShifts_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Shifts.
        /// </summary>
        public static string MultipleShifts_En {
            get {
                return ResourceManager.GetString("MultipleShifts_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العديد من الحالات.
        /// </summary>
        public static string MultipleStatuses_Ar {
            get {
                return ResourceManager.GetString("MultipleStatuses_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Statuses.
        /// </summary>
        public static string MultipleStatuses_En {
            get {
                return ResourceManager.GetString("MultipleStatuses_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مفعل.
        /// </summary>
        public static string NotActive_Ar {
            get {
                return ResourceManager.GetString("NotActive_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        public static string NotActive_En {
            get {
                return ResourceManager.GetString("NotActive_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Failed..
        /// </summary>
        public static string SavedFailed {
            get {
                return ResourceManager.GetString("SavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeeded.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select An Item..
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift activated Successfully.
        /// </summary>
        public static string ShiftActivatedSuccess {
            get {
                return ResourceManager.GetString("ShiftActivatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Deactivated Successfully.
        /// </summary>
        public static string ShiftDeactivatedSuccess {
            get {
                return ResourceManager.GetString("ShiftDeactivatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized to access Dashboard.
        /// </summary>
        public static string UnauthorizedDashboard {
            get {
                return ResourceManager.GetString("UnauthorizedDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized to access Holidays.
        /// </summary>
        public static string UnauthorizedHolidays {
            get {
                return ResourceManager.GetString("UnauthorizedHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjustified.
        /// </summary>
        public static string Unjustified {
            get {
                return ResourceManager.GetString("Unjustified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مجدول.
        /// </summary>
        public static string UnScheduled_Ar {
            get {
                return ResourceManager.GetString("UnScheduled_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnScheduled.
        /// </summary>
        public static string UnScheduled_En {
            get {
                return ResourceManager.GetString("UnScheduled_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved failed due to validation error..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل فى عطلة.
        /// </summary>
        public static string WorkOnHoliday_Ar {
            get {
                return ResourceManager.GetString("WorkOnHoliday_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work On Holiday.
        /// </summary>
        public static string WorkOnHoliday_En {
            get {
                return ResourceManager.GetString("WorkOnHoliday_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل فى اجازة.
        /// </summary>
        public static string WorkOnLeave_Ar {
            get {
                return ResourceManager.GetString("WorkOnLeave_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work On Leave.
        /// </summary>
        public static string WorkOnLeave_En {
            get {
                return ResourceManager.GetString("WorkOnLeave_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل فى نهاية الاسبوع.
        /// </summary>
        public static string WorkOnWeekend_Ar {
            get {
                return ResourceManager.GetString("WorkOnWeekend_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work on Weekend.
        /// </summary>
        public static string WorkOnWeekend_En {
            get {
                return ResourceManager.GetString("WorkOnWeekend_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
