//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.Tamam.Resources.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Leaves {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Leaves() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADS.Tamam.Resources.Culture.Leaves", typeof(Leaves).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Excuse for {0} duration exceeds your available Credit for this month.
        /// </summary>
        public static string ExceedExcusesCredit {
            get {
                return ResourceManager.GetString("ExceedExcusesCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more excuses for {0} available for this day.
        /// </summary>
        public static string ExceedExcusesCreditDay {
            get {
                return ResourceManager.GetString("ExceedExcusesCreditDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Excuse for {0} duration exceeds your available Credit for this day.
        /// </summary>
        public static string ExceedExcusesCreditDay2 {
            get {
                return ResourceManager.GetString("ExceedExcusesCreditDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the unTransferred Leaves Credit People.
        /// </summary>
        public static string GetPeopleFaild {
            get {
                return ResourceManager.GetString("GetPeopleFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid leave type / no relevant policy associated.
        /// </summary>
        public static string InvalidLeaveType {
            get {
                return ResourceManager.GetString("InvalidLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Excuses for {0} Credit available for this month.
        /// </summary>
        public static string NoExcusesCredit {
            get {
                return ResourceManager.GetString("NoExcusesCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Excuse for {0} duration must be at minimum {1} hours.
        /// </summary>
        public static string NoExcusesCreditHours {
            get {
                return ResourceManager.GetString("NoExcusesCreditHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select only one person.
        /// </summary>
        public static string SelectOnlyOnePerson {
            get {
                return ResourceManager.GetString("SelectOnlyOnePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Transfer Credits.
        /// </summary>
        public static string TransferFaild {
            get {
                return ResourceManager.GetString("TransferFaild", resourceCulture);
            }
        }
    }
}
