//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.Tamam.Resources.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Organization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Organization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADS.Tamam.Resources.Culture.Organization", typeof(Organization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الموافقة عليه.
        /// </summary>
        public static string ApprovedAr {
            get {
                return ResourceManager.GetString("ApprovedAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve / Reject.
        /// </summary>
        public static string ApproveReject {
            get {
                return ResourceManager.GetString("ApproveReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافقة / رفض.
        /// </summary>
        public static string ApproveRejectAr {
            get {
                return ResourceManager.GetString("ApproveRejectAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغائه.
        /// </summary>
        public static string CancelledAr {
            get {
                return ResourceManager.GetString("CancelledAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Request Failed.
        /// </summary>
        public static string CreateRequestFailed {
            get {
                return ResourceManager.GetString("CreateRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this node due to it has child nodes or person..
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Department.
        /// </summary>
        public static string InvalidDepartment {
            get {
                return ResourceManager.GetString("InvalidDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string ManualAttendanceApproval_AttendanceType_In {
            get {
                return ResourceManager.GetString("ManualAttendanceApproval_AttendanceType_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string ManualAttendanceApproval_AttendanceType_InAr {
            get {
                return ResourceManager.GetString("ManualAttendanceApproval_AttendanceType_InAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string ManualAttendanceApproval_AttendanceType_Out {
            get {
                return ResourceManager.GetString("ManualAttendanceApproval_AttendanceType_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string ManualAttendanceApproval_AttendanceType_OutAr {
            get {
                return ResourceManager.GetString("ManualAttendanceApproval_AttendanceType_OutAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty).
        /// </summary>
        public static string ManualAttendanceApproval_Empty {
            get {
                return ResourceManager.GetString("ManualAttendanceApproval_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (فارغ).
        /// </summary>
        public static string ManualAttendanceApproval_EmptyAr {
            get {
                return ResourceManager.GetString("ManualAttendanceApproval_EmptyAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الموافقة عليه.
        /// </summary>
        public static string RejectedAr {
            get {
                return ResourceManager.GetString("RejectedAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   View .
        /// </summary>
        public static string RequestStatusView {
            get {
                return ResourceManager.GetString("RequestStatusView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عرض.
        /// </summary>
        public static string RequestStatusViewAr {
            get {
                return ResourceManager.GetString("RequestStatusViewAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Parent.
        /// </summary>
        public static string SelectParent {
            get {
                return ResourceManager.GetString("SelectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string ViewAr {
            get {
                return ResourceManager.GetString("ViewAr", resourceCulture);
            }
        }
    }
}
