//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.Tamam.Resources.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADS.Tamam.Resources.Culture.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Steps Sequance should be Unique.
        /// </summary>
        public static string ApprovalStepsUnique {
            get {
                return ResourceManager.GetString("ApprovalStepsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name is not provided.
        /// </summary>
        public static string ArabicNameEmpty {
            get {
                return ResourceManager.GetString("ArabicNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name Should not Exceed 200.
        /// </summary>
        public static string ArabicNameLength {
            get {
                return ResourceManager.GetString("ArabicNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name length should not exceed {0}.
        /// </summary>
        public static string ArabicNameLengthInvalid {
            get {
                return ResourceManager.GetString("ArabicNameLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Code is already used in another one.
        /// </summary>
        public static string AttendanceCodeIsCodeUnique {
            get {
                return ResourceManager.GetString("AttendanceCodeIsCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code cannot be null or empty.
        /// </summary>
        public static string AttendanceCodeIsEmpty {
            get {
                return ResourceManager.GetString("AttendanceCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string AttendanceDateMissing {
            get {
                return ResourceManager.GetString("AttendanceDateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment length should not exceed 100.
        /// </summary>
        public static string CommentIncorrect {
            get {
                return ResourceManager.GetString("CommentIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Comment.
        /// </summary>
        public static string CommentMissing {
            get {
                return ResourceManager.GetString("CommentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is not provided.
        /// </summary>
        public static string DelegateIdEmpty {
            get {
                return ResourceManager.GetString("DelegateIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code should be unique.
        /// </summary>
        public static string DepartmentCodeUnique {
            get {
                return ResourceManager.GetString("DepartmentCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This department can not be deleted. It has other departments or people.
        /// </summary>
        public static string DepartmentDeleteFailed {
            get {
                return ResourceManager.GetString("DepartmentDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This department can not be deleted. It has one or more scheduled reports.
        /// </summary>
        public static string DepartmentDeleteFailed_RelatedScheduledReports {
            get {
                return ResourceManager.GetString("DepartmentDeleteFailed_RelatedScheduledReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This department can not be deleted. It has one or more schedules.
        /// </summary>
        public static string DepartmentDeleteFailed_RelatedSchedules {
            get {
                return ResourceManager.GetString("DepartmentDeleteFailed_RelatedSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description should not exceed 200 character.
        /// </summary>
        public static string DepartmentDescriptionLength {
            get {
                return ResourceManager.GetString("DepartmentDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is not provided.
        /// </summary>
        public static string DepartmentIdEmpty {
            get {
                return ResourceManager.GetString("DepartmentIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name (Culture Variant) is not provided.
        /// </summary>
        public static string DepartmentNameCultureVariantEmpty {
            get {
                return ResourceManager.GetString("DepartmentNameCultureVariantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name is not provided.
        /// </summary>
        public static string DepartmentNameEmpty {
            get {
                return ResourceManager.GetString("DepartmentNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name should be unique for every level.
        /// </summary>
        public static string DepartmentNameUnique {
            get {
                return ResourceManager.GetString("DepartmentNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Parent Can not be the department itself.
        /// </summary>
        public static string DepartmentParentEqSelf {
            get {
                return ResourceManager.GetString("DepartmentParentEqSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent department is not provided.
        /// </summary>
        public static string DepartmentParentInvalid {
            get {
                return ResourceManager.GetString("DepartmentParentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent department cant be a child of the same department.
        /// </summary>
        public static string DepartmentParentRecursive {
            get {
                return ResourceManager.GetString("DepartmentParentRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Cannot be deleted, It&apos;s being used in Department Rule Policy.
        /// </summary>
        public static string DepartmentUsedInPolicy {
            get {
                return ResourceManager.GetString("DepartmentUsedInPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Manager Sequance is not valid.
        /// </summary>
        public static string DirectManagerSequanceEmpty {
            get {
                return ResourceManager.GetString("DirectManagerSequanceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some duplicates in people data.
        /// </summary>
        public static string DuplicatePersonId {
            get {
                return ResourceManager.GetString("DuplicatePersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When editing taken leave you can only edit it&apos;s notes or attachments.
        /// </summary>
        public static string EditCanceledLeaveWithUnexpectedValues {
            get {
                return ResourceManager.GetString("EditCanceledLeaveWithUnexpectedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When editing taken excuse you can only edit it&apos;s notes or attachments.
        /// </summary>
        public static string EditTakenExcuse {
            get {
                return ResourceManager.GetString("EditTakenExcuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Type is not provided.
        /// </summary>
        public static string EmploymentTypeEmpty {
            get {
                return ResourceManager.GetString("EmploymentTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either person or email should be provided.
        /// </summary>
        public static string EmptyPersonAndEmail {
            get {
                return ResourceManager.GetString("EmptyPersonAndEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is not provided.
        /// </summary>
        public static string EndDateEmpty {
            get {
                return ResourceManager.GetString("EndDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date should be greater than Start Date.
        /// </summary>
        public static string EndDateShouldGreaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateShouldGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time is not provided.
        /// </summary>
        public static string EndTimeEmpty {
            get {
                return ResourceManager.GetString("EndTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse for {0} can not to be cancelled.
        /// </summary>
        public static string ExcuseCanCancelled {
            get {
                return ResourceManager.GetString("ExcuseCanCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse for {0} can not be reviewed.
        /// </summary>
        public static string ExcuseCanReviewed {
            get {
                return ResourceManager.GetString("ExcuseCanReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse for {0} Date is not provided.
        /// </summary>
        public static string ExcuseDateEmpty {
            get {
                return ResourceManager.GetString("ExcuseDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts for you in this time frame.
        /// </summary>
        public static string ExcuseDurationEqualZero {
            get {
                return ResourceManager.GetString("ExcuseDurationEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts for {0} in this time frame.
        /// </summary>
        public static string ExcuseDurationForPersonNameEqualZero {
            get {
                return ResourceManager.GetString("ExcuseDurationForPersonNameEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse for {0} End Time is not provided.
        /// </summary>
        public static string ExcuseEndTimeEmpty {
            get {
                return ResourceManager.GetString("ExcuseEndTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a leave in this day. It is not supported to have a leave and an excuse in the same day..
        /// </summary>
        public static string ExcuseForPersonConflictWithLeave {
            get {
                return ResourceManager.GetString("ExcuseForPersonConflictWithLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} End Time must be greater than Start Time.
        /// </summary>
        public static string ExcuseInvalidEndTime {
            get {
                return ResourceManager.GetString("ExcuseInvalidEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name is not provided.
        /// </summary>
        public static string ExcusePersonEmpty {
            get {
                return ResourceManager.GetString("ExcusePersonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse for {0} Start Time is not provided.
        /// </summary>
        public static string ExcuseStartTimeEmpty {
            get {
                return ResourceManager.GetString("ExcuseStartTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse for {0} Status is not provided.
        /// </summary>
        public static string ExcuseStatusEmpty {
            get {
                return ResourceManager.GetString("ExcuseStatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse type not provided.
        /// </summary>
        public static string ExcuseTypeEmpty {
            get {
                return ResourceManager.GetString("ExcuseTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} for person {1} overlaps with another excuse or away.
        /// </summary>
        public static string ExcuseUnique {
            get {
                return ResourceManager.GetString("ExcuseUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is not provided.
        /// </summary>
        public static string HolidayCodeEmpty {
            get {
                return ResourceManager.GetString("HolidayCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should be within 1 and 50 letters.
        /// </summary>
        public static string HolidayCodeLength {
            get {
                return ResourceManager.GetString("HolidayCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Should be Unique.
        /// </summary>
        public static string HolidayCodeUnique {
            get {
                return ResourceManager.GetString("HolidayCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly Enter Valid HR Role.
        /// </summary>
        public static string HRRoleEmpty {
            get {
                return ResourceManager.GetString("HRRoleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Sequance is not valid.
        /// </summary>
        public static string HRSequanceEmpty {
            get {
                return ResourceManager.GetString("HRSequanceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code, Email, or Username need to be Unique.
        /// </summary>
        public static string IdentifierUnique {
            get {
                return ResourceManager.GetString("IdentifierUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Approval Policy.
        /// </summary>
        public static string InvalidApprovalPolicy {
            get {
                return ResourceManager.GetString("InvalidApprovalPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CCs Email Address Format.
        /// </summary>
        public static string InvalidCCs {
            get {
                return ResourceManager.GetString("InvalidCCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave for {0} status must be Pending or Planned.
        /// </summary>
        public static string InvalidCreateLeaveStatus {
            get {
                return ResourceManager.GetString("InvalidCreateLeaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates orders are invalid.
        /// </summary>
        public static string InvalidDatesOrder {
            get {
                return ResourceManager.GetString("InvalidDatesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Day.
        /// </summary>
        public static string InvalidDay {
            get {
                return ResourceManager.GetString("InvalidDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift duration should be greater than 0 and less than 24 hour ( or less than 48 for night shifts ).
        /// </summary>
        public static string InValidDuration {
            get {
                return ResourceManager.GetString("InValidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply multiple pending manual attendance at the same time.
        /// </summary>
        public static string InvalidEditAttendanceEvent {
            get {
                return ResourceManager.GetString("InvalidEditAttendanceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address Format.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid end time.
        /// </summary>
        public static string InvalidEndTime {
            get {
                return ResourceManager.GetString("InvalidEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} date must be in the previous, current or next month.
        /// </summary>
        public static string InvalidExcuseCreationDate {
            get {
                return ResourceManager.GetString("InvalidExcuseCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed hours per day is not valid.
        /// </summary>
        public static string InvalidExcusePolicyAllowedHoursPerDay {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyAllowedHoursPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For excuse that has no credit Allowed hours per day must be empty or zero.
        /// </summary>
        public static string InvalidExcusePolicyAllowedHoursPerDay_NoCredit {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyAllowedHoursPerDay_NoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed hours per month is not valid.
        /// </summary>
        public static string InvalidExcusePolicyAllowedHoursPerMonth {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyAllowedHoursPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For excuse that has no credit Allowed hours per month must be empty or zero.
        /// </summary>
        public static string InvalidExcusePolicyAllowedHoursPerMonth_NoCredit {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyAllowedHoursPerMonth_NoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum excuses per day is not valid.
        /// </summary>
        public static string InvalidExcusePolicyMaxExcusesPerDay {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyMaxExcusesPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For excuse that has no credit Maximum excuses per day must be empty or zero.
        /// </summary>
        public static string InvalidExcusePolicyMaxExcusesPerDay_NoCredit {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyMaxExcusesPerDay_NoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum excuses per month is not valid.
        /// </summary>
        public static string InvalidExcusePolicyMaxExcusesPerMonth {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyMaxExcusesPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For excuse that has no credit Maximum excuses per month must be empty or zero.
        /// </summary>
        public static string InvalidExcusePolicyMaxExcusesPerMonth_NoCredit {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyMaxExcusesPerMonth_NoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum duration per excuse is not valid.
        /// </summary>
        public static string InvalidExcusePolicyMinDurationPerExcuse {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyMinDurationPerExcuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For excuse that has no credit Minimum duration per excuse must be empty or zero.
        /// </summary>
        public static string InvalidExcusePolicyMinDurationPerExcuse_NoCredit {
            get {
                return ResourceManager.GetString("InvalidExcusePolicyMinDurationPerExcuse_NoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} date must be in the remaining days of the current month or in the next month.
        /// </summary>
        public static string InvalidExcuseRequestDate {
            get {
                return ResourceManager.GetString("InvalidExcuseRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Excuse Status for Integration Mode.
        /// </summary>
        public static string InvalidExcuseStatusIntegrationMode {
            get {
                return ResourceManager.GetString("InvalidExcuseStatusIntegrationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax must be at maximum 20 number.
        /// </summary>
        public static string InvalidFaxLength {
            get {
                return ResourceManager.GetString("InvalidFaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Gender.
        /// </summary>
        public static string InvalidGenderId {
            get {
                return ResourceManager.GetString("InvalidGenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department should be selected to be able to send to the supervisor.
        /// </summary>
        public static string InvalidIncludeSupervisor {
            get {
                return ResourceManager.GetString("InvalidIncludeSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Amount is not valid.
        /// </summary>
        public static string InvalidLeavePolicyAmount {
            get {
                return ResourceManager.GetString("InvalidLeavePolicyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Carry Over Days is not valid.
        /// </summary>
        public static string InvalidLeavePolicyCarryOver {
            get {
                return ResourceManager.GetString("InvalidLeavePolicyCarryOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Before request is not valid.
        /// </summary>
        public static string InvalidLeavePolicyRequest {
            get {
                return ResourceManager.GetString("InvalidLeavePolicyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Leave Type.
        /// </summary>
        public static string InvalidLeaveType {
            get {
                return ResourceManager.GetString("InvalidLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night shift cannot be flexible.
        /// </summary>
        public static string InValidNightFlexibleCombination {
            get {
                return ResourceManager.GetString("InValidNightFlexibleCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected person doesn&apos;t have that report privileges.
        /// </summary>
        public static string InvalidPersonReportPrivilage {
            get {
                return ResourceManager.GetString("InvalidPersonReportPrivilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone must be at maximum 20 number.
        /// </summary>
        public static string InvalidPhoneLength {
            get {
                return ResourceManager.GetString("InvalidPhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some duplicates in schedule times for departments.
        /// </summary>
        public static string InvalidScheduleDepartment_Duplicates {
            get {
                return ResourceManager.GetString("InvalidScheduleDepartment_Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some overlaps in schedule times for departments.
        /// </summary>
        public static string InvalidScheduleDepartment_Overlap {
            get {
                return ResourceManager.GetString("InvalidScheduleDepartment_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some overlaps in schedule times for departments with other schedules.
        /// </summary>
        public static string InvalidScheduleDepartment_OverlapWithOtherSchedules {
            get {
                return ResourceManager.GetString("InvalidScheduleDepartment_OverlapWithOtherSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules dates for departments should be in schedule date range.
        /// </summary>
        public static string InvalidScheduleDepartment_ScheduleDateRange {
            get {
                return ResourceManager.GetString("InvalidScheduleDepartment_ScheduleDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date for departments schedules should be greater than or equal start date.
        /// </summary>
        public static string InvalidScheduleDepartment_StartDateEndDate {
            get {
                return ResourceManager.GetString("InvalidScheduleDepartment_StartDateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the selected persons have a schedule overlapping with this schedule.
        /// </summary>
        public static string InvalidSchedulePerson {
            get {
                return ResourceManager.GetString("InvalidSchedulePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some duplicates in schedule times for personnel.
        /// </summary>
        public static string InvalidSchedulePersonnel_Duplicates {
            get {
                return ResourceManager.GetString("InvalidSchedulePersonnel_Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only assign a schedule to personnel after their joining date. Please select a start date &gt; joining date.
        /// </summary>
        public static string InvalidSchedulePersonnel_HireDate {
            get {
                return ResourceManager.GetString("InvalidSchedulePersonnel_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some overlaps in schedule times for personnel.
        /// </summary>
        public static string InvalidSchedulePersonnel_Overlap {
            get {
                return ResourceManager.GetString("InvalidSchedulePersonnel_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some overlaps in schedule times for personnel with other schedules.
        /// </summary>
        public static string InvalidSchedulePersonnel_OverlapWithOtherSchedules {
            get {
                return ResourceManager.GetString("InvalidSchedulePersonnel_OverlapWithOtherSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules dates for personnel should be in schedule date range.
        /// </summary>
        public static string InvalidSchedulePersonnel_ScheduleDateRange {
            get {
                return ResourceManager.GetString("InvalidSchedulePersonnel_ScheduleDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date for personnel schedules should be greater than or equal start date.
        /// </summary>
        public static string InvalidSchedulePersonnel_StartDateEndDate {
            get {
                return ResourceManager.GetString("InvalidSchedulePersonnel_StartDateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Policy is not valid.
        /// </summary>
        public static string InvalidShiftPolicy {
            get {
                return ResourceManager.GetString("InvalidShiftPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift start or end time is not valid.
        /// </summary>
        public static string InvalidShiftTimes {
            get {
                return ResourceManager.GetString("InvalidShiftTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start time.
        /// </summary>
        public static string InvalidStartTime {
            get {
                return ResourceManager.GetString("InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave status must be Approved.
        /// </summary>
        public static string InvalidSystemCreateLeaveStatus {
            get {
                return ResourceManager.GetString("InvalidSystemCreateLeaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be one target at least for the report.
        /// </summary>
        public static string InvalidTarget {
            get {
                return ResourceManager.GetString("InvalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid job title.
        /// </summary>
        public static string InvalidTitleId {
            get {
                return ResourceManager.GetString("InvalidTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IsNative] value invalid.
        /// </summary>
        public static string IsNative {
            get {
                return ResourceManager.GetString("IsNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title is not provided.
        /// </summary>
        public static string JobTitleEmpty {
            get {
                return ResourceManager.GetString("JobTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments required for this leave type for {0}.
        /// </summary>
        public static string LeaveAttachmentRequired {
            get {
                return ResourceManager.GetString("LeaveAttachmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This leave for {0} can not to be cancelled.
        /// </summary>
        public static string LeaveCanCancelled {
            get {
                return ResourceManager.GetString("LeaveCanCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave for {0} can not to be edited.
        /// </summary>
        public static string LeaveCanEdit {
            get {
                return ResourceManager.GetString("LeaveCanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave can not to be reviewed.
        /// </summary>
        public static string LeaveCanReviewed {
            get {
                return ResourceManager.GetString("LeaveCanReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave days should not exceed {0}.
        /// </summary>
        public static string LeaveEffectiveDayNotVaild {
            get {
                return ResourceManager.GetString("LeaveEffectiveDayNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No working days in this time frame for {0}.
        /// </summary>
        public static string LeaveEffectiveDaysEqualZero {
            get {
                return ResourceManager.GetString("LeaveEffectiveDaysEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave End Date for {0} is not provided.
        /// </summary>
        public static string LeaveEndDateEmpty {
            get {
                return ResourceManager.GetString("LeaveEndDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Day Leave for {0} should be applied on only one single day.
        /// </summary>
        public static string LeaveHalfDayInvalid {
            get {
                return ResourceManager.GetString("LeaveHalfDayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t request half day for this leave type for {0}.
        /// </summary>
        public static string LeaveHalfDayNotAllowed {
            get {
                return ResourceManager.GetString("LeaveHalfDayNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no association to the requested leave type.
        /// </summary>
        public static string LeaveInvalidLeaveTypePolicy {
            get {
                return ResourceManager.GetString("LeaveInvalidLeaveTypePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave End Date for {0} must be greater than or equal to Leave Start Date.
        /// </summary>
        public static string LeaveInvalidStartAndEndDate {
            get {
                return ResourceManager.GetString("LeaveInvalidStartAndEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave for {0} is outside current credit year.
        /// </summary>
        public static string LeaveOutCredit {
            get {
                return ResourceManager.GetString("LeaveOutCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person {0} is not active.
        /// </summary>
        public static string LeavePersonNotActive {
            get {
                return ResourceManager.GetString("LeavePersonNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0} days before leave start date.
        /// </summary>
        public static string LeaveRequestDaysBefore {
            get {
                return ResourceManager.GetString("LeaveRequestDaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to request leave.
        /// </summary>
        public static string LeaveRequestNotAllowed {
            get {
                return ResourceManager.GetString("LeaveRequestNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not request leave for old dates.
        /// </summary>
        public static string LeaveRequestOldDate {
            get {
                return ResourceManager.GetString("LeaveRequestOldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave for {0} Start Date is not provided.
        /// </summary>
        public static string LeaveStartDateEmpty {
            get {
                return ResourceManager.GetString("LeaveStartDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave for {0} Start exceeds days limit for old leaves.
        /// </summary>
        public static string LeaveStartDateExceedsOldLeavesDaysLimit {
            get {
                return ResourceManager.GetString("LeaveStartDateExceedsOldLeavesDaysLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave for {0} Start is before Leave credit effective date..
        /// </summary>
        public static string LeaveStartDateInvalid {
            get {
                return ResourceManager.GetString("LeaveStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Status for {0} is not provided.
        /// </summary>
        public static string LeaveStatusIdEmpty {
            get {
                return ResourceManager.GetString("LeaveStatusIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Credit available for this leave type for {0}.
        /// </summary>
        public static string LeaveTypeHasNoCredit {
            get {
                return ResourceManager.GetString("LeaveTypeHasNoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type for {0} is not provided.
        /// </summary>
        public static string LeaveTypeIdEmpty {
            get {
                return ResourceManager.GetString("LeaveTypeIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave dates for {0} overlaps with another one.
        /// </summary>
        public static string LeaveUnique {
            get {
                return ResourceManager.GetString("LeaveUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic) is not provided.
        /// </summary>
        public static string NameArabicEmpty {
            get {
                return ResourceManager.GetString("NameArabicEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic) should be Unique.
        /// </summary>
        public static string NameCultureVariantNotUnique {
            get {
                return ResourceManager.GetString("NameCultureVariantNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not provided.
        /// </summary>
        public static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Should not Exceed 200.
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should not exceed {0}.
        /// </summary>
        public static string NameLengthInvalid {
            get {
                return ResourceManager.GetString("NameLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be Unique.
        /// </summary>
        public static string NameNotUnique {
            get {
                return ResourceManager.GetString("NameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Code is not provided.
        /// </summary>
        public static string OrganizationDetailCodeEmpty {
            get {
                return ResourceManager.GetString("OrganizationDetailCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name (Culture Variant) is not provided.
        /// </summary>
        public static string OrganizationDetailNameCultureVariantEmpty {
            get {
                return ResourceManager.GetString("OrganizationDetailNameCultureVariantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name is not provided.
        /// </summary>
        public static string OrganizationDetailNameEmpty {
            get {
                return ResourceManager.GetString("OrganizationDetailNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address length should not exceed 200 characters.
        /// </summary>
        public static string PersonAddressLength {
            get {
                return ResourceManager.GetString("PersonAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date is not provided.
        /// </summary>
        public static string PersonBirthDateEmpty {
            get {
                return ResourceManager.GetString("PersonBirthDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee age is not valid when joining the company.
        /// </summary>
        public static string PersonBirthDateInvalid {
            get {
                return ResourceManager.GetString("PersonBirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code and Email should not be the same.
        /// </summary>
        public static string PersonCodeEmailInvalid {
            get {
                return ResourceManager.GetString("PersonCodeEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Code is not provided.
        /// </summary>
        public static string PersonCodeEmpty {
            get {
                return ResourceManager.GetString("PersonCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should be within 1 and 50 letters.
        /// </summary>
        public static string PersonCodeLength {
            get {
                return ResourceManager.GetString("PersonCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Code Should be Unique.
        /// </summary>
        public static string PersonCodeUnique {
            get {
                return ResourceManager.GetString("PersonCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code and username should not be the same.
        /// </summary>
        public static string PersonCodeUsernameInvalid {
            get {
                return ResourceManager.GetString("PersonCodeUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Department is not provided.
        /// </summary>
        public static string PersonDepartmentEmpty {
            get {
                return ResourceManager.GetString("PersonDepartmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email should not exceed 50 characters.
        /// </summary>
        public static string PersonEmailLength {
            get {
                return ResourceManager.GetString("PersonEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Email Should be Unique.
        /// </summary>
        public static string PersonEmailUnique {
            get {
                return ResourceManager.GetString("PersonEmailUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name (Arabic) is not provided.
        /// </summary>
        public static string PersonFullNameCultureVariantEmpty {
            get {
                return ResourceManager.GetString("PersonFullNameCultureVariantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name (Arabic) should be within 4 and 100 letters.
        /// </summary>
        public static string PersonFullNameCultureVariantLength {
            get {
                return ResourceManager.GetString("PersonFullNameCultureVariantLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name is not provided.
        /// </summary>
        public static string PersonFullNameEmpty {
            get {
                return ResourceManager.GetString("PersonFullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name should be within 4 and 100 letters.
        /// </summary>
        public static string PersonFullNameLength {
            get {
                return ResourceManager.GetString("PersonFullNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no policy for this excuse type.
        /// </summary>
        public static string PersonHasNoPolicyForExcuseType {
            get {
                return ResourceManager.GetString("PersonHasNoPolicyForExcuseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name is not provided.
        /// </summary>
        public static string PersonIdEmpty {
            get {
                return ResourceManager.GetString("PersonIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Id.
        /// </summary>
        public static string PersonInvalidUserId {
            get {
                return ResourceManager.GetString("PersonInvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Person Cannot be deactivated because someone else is reporting to him.
        /// </summary>
        public static string PersonIsManager {
            get {
                return ResourceManager.GetString("PersonIsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Join Date is not provided.
        /// </summary>
        public static string PersonJoinDateEmpty {
            get {
                return ResourceManager.GetString("PersonJoinDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date is not valid in regards to the Birthdate or the Creation Date.
        /// </summary>
        public static string PersonJoinDateGreaterThanBirthDate {
            get {
                return ResourceManager.GetString("PersonJoinDateGreaterThanBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Person.
        /// </summary>
        public static string PersonMissing {
            get {
                return ResourceManager.GetString("PersonMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number length should not exceed 40 digits.
        /// </summary>
        public static string PersonPassportNumberLength {
            get {
                return ResourceManager.GetString("PersonPassportNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Civil No. should be between 6 and 40 characters.
        /// </summary>
        public static string PersonSSNLength {
            get {
                return ResourceManager.GetString("PersonSSNLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id already associated with another Person.
        /// </summary>
        public static string PersonUserIdIsUnique {
            get {
                return ResourceManager.GetString("PersonUserIdIsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Email should not be the same.
        /// </summary>
        public static string PersonUsernameEmailInvalid {
            get {
                return ResourceManager.GetString("PersonUsernameEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be unique.
        /// </summary>
        public static string PersonUsernameUnique {
            get {
                return ResourceManager.GetString("PersonUsernameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be unique, Person cannot be edited while his identity is not valid.
        /// </summary>
        public static string PersonUsernameUniqueEditMode {
            get {
                return ResourceManager.GetString("PersonUsernameUniqueEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned leaves not allowed for this leave type..
        /// </summary>
        public static string PlannedLeavesNotAllow {
            get {
                return ResourceManager.GetString("PlannedLeavesNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy is being associated with Policy Groups.
        /// </summary>
        public static string PolicyAssociationsCheck {
            get {
                return ResourceManager.GetString("PolicyAssociationsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy is being associated with Shifts.
        /// </summary>
        public static string PolicyAssociationsWithShift {
            get {
                return ResourceManager.GetString("PolicyAssociationsWithShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Code is not provided.
        /// </summary>
        public static string PolicyCodeEmpty {
            get {
                return ResourceManager.GetString("PolicyCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code length is not valid.
        /// </summary>
        public static string PolicyCodeLength {
            get {
                return ResourceManager.GetString("PolicyCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Code Should be Unique.
        /// </summary>
        public static string PolicyCodeUnique {
            get {
                return ResourceManager.GetString("PolicyCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy cannot be deleted because some other policy is associated with it.
        /// </summary>
        public static string PolicyDeleteFail {
            get {
                return ResourceManager.GetString("PolicyDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type is not provided.
        /// </summary>
        public static string PolicyFieldDataTypeEmpty {
            get {
                return ResourceManager.GetString("PolicyFieldDataTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type Invalid.
        /// </summary>
        public static string PolicyFieldDataTypeInvalid {
            get {
                return ResourceManager.GetString("PolicyFieldDataTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Id is not provided.
        /// </summary>
        public static string PolicyFieldReferenceIdInvalid {
            get {
                return ResourceManager.GetString("PolicyFieldReferenceIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reference Type. For List Data Type Reference Type can not be empty.
        /// </summary>
        public static string PolicyFieldReferenceTypeInvalid {
            get {
                return ResourceManager.GetString("PolicyFieldReferenceTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence is not valid.
        /// </summary>
        public static string PolicyFieldSequanceInValid {
            get {
                return ResourceManager.GetString("PolicyFieldSequanceInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Group Arabic Name is not provided.
        /// </summary>
        public static string PolicyGroupArabicNameEmpty {
            get {
                return ResourceManager.GetString("PolicyGroupArabicNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Group can not be Deleted, because it may be associated with personnel or departments or policies.
        /// </summary>
        public static string PolicyGroupHaveAssociations {
            get {
                return ResourceManager.GetString("PolicyGroupHaveAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Group Name is not provided.
        /// </summary>
        public static string PolicyGroupNameEmpty {
            get {
                return ResourceManager.GetString("PolicyGroupNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name (Arabic) Should not Exceed 200.
        /// </summary>
        public static string PolicyNameCultureVariantLength {
            get {
                return ResourceManager.GetString("PolicyNameCultureVariantLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name (Arabic) Should be Unique.
        /// </summary>
        public static string PolicyNameCultureVariantUnique {
            get {
                return ResourceManager.GetString("PolicyNameCultureVariantUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name Should not Exceed 200.
        /// </summary>
        public static string PolicyNameLength {
            get {
                return ResourceManager.GetString("PolicyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name Should be Unique.
        /// </summary>
        public static string PolicyNameUnique {
            get {
                return ResourceManager.GetString("PolicyNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Type is Not Valid.
        /// </summary>
        public static string PolicyTypeNotValid {
            get {
                return ResourceManager.GetString("PolicyTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Values are not valid.
        /// </summary>
        public static string PolicyValuesCheck {
            get {
                return ResourceManager.GetString("PolicyValuesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report is not provided.
        /// </summary>
        public static string ReportIdEmpty {
            get {
                return ResourceManager.GetString("ReportIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Attendance Event.
        /// </summary>
        public static string ScheduleEventMissing {
            get {
                return ResourceManager.GetString("ScheduleEventMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is not provided.
        /// </summary>
        public static string ScheduleRequired {
            get {
                return ResourceManager.GetString("ScheduleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Template is not provided.
        /// </summary>
        public static string ScheduleTemplateEmpty {
            get {
                return ResourceManager.GetString("ScheduleTemplateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly template can not repeat greater or less than one time.
        /// </summary>
        public static string ScheduleTemplateMonthRepeat {
            get {
                return ResourceManager.GetString("ScheduleTemplateMonthRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template must have at most one flexible shift per day.
        /// </summary>
        public static string ScheduleTemplateMoreThanOneFlexible {
            get {
                return ResourceManager.GetString("ScheduleTemplateMoreThanOneFlexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name is not valid.
        /// </summary>
        public static string ScheduleTemplateNameNotValid {
            get {
                return ResourceManager.GetString("ScheduleTemplateNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template must have at least one detail with shift.
        /// </summary>
        public static string ScheduleTemplateNoDetails {
            get {
                return ResourceManager.GetString("ScheduleTemplateNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel or department should be provided.
        /// </summary>
        public static string ScheduleTemplatePersonAndDepartmentEmpty {
            get {
                return ResourceManager.GetString("ScheduleTemplatePersonAndDepartmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat is not provided.
        /// </summary>
        public static string ScheduleTemplateRepeatEmpty {
            get {
                return ResourceManager.GetString("ScheduleTemplateRepeatEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Type is not provided.
        /// </summary>
        public static string ScheduleTemplateRepeatTypeEmpty {
            get {
                return ResourceManager.GetString("ScheduleTemplateRepeatTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Repeat cant exceed 6.
        /// </summary>
        public static string ScheduleTemplateWeekRepeat {
            get {
                return ResourceManager.GetString("ScheduleTemplateWeekRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Id Should not Exceed 100.
        /// </summary>
        public static string SecurityIdLength {
            get {
                return ResourceManager.GetString("SecurityIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift can not be deleted or deactivated because it has been associated with a policy.
        /// </summary>
        public static string ShiftHavePolicies {
            get {
                return ResourceManager.GetString("ShiftHavePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift can not be deleted or deactivated because it has been associated with a schedule template.
        /// </summary>
        public static string ShiftHaveTemplates {
            get {
                return ResourceManager.GetString("ShiftHaveTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new shift time Overlap with another shift time associated in the same Schedule Template.
        /// </summary>
        public static string ShiftInTemplatesOverlap {
            get {
                return ResourceManager.GetString("ShiftInTemplatesOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the selected shifts overlap in times.
        /// </summary>
        public static string ShiftOverlap {
            get {
                return ResourceManager.GetString("ShiftOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift start cant be equal to shift end.
        /// </summary>
        public static string ShiftStartEqEnd {
            get {
                return ResourceManager.GetString("ShiftStartEqEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is not provided.
        /// </summary>
        public static string StartDateEmpty {
            get {
                return ResourceManager.GetString("StartDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date must be less than or equal to end date.
        /// </summary>
        public static string StartDateLessEndDate {
            get {
                return ResourceManager.GetString("StartDateLessEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is not provided.
        /// </summary>
        public static string StartTimeEmpty {
            get {
                return ResourceManager.GetString("StartTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Manager Sequance is not valid.
        /// </summary>
        public static string SuperManagerSequanceEmpty {
            get {
                return ResourceManager.GetString("SuperManagerSequanceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Supervisor Must be from the same department.
        /// </summary>
        public static string SupervisorNotVaild {
            get {
                return ResourceManager.GetString("SupervisorNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template can not be deleted or deactivated because it has been associated with a schedule.
        /// </summary>
        public static string TemplateHaveSchedule {
            get {
                return ResourceManager.GetString("TemplateHaveSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer period is out of the schedule available period.
        /// </summary>
        public static string TransferScheduleInvalidDate {
            get {
                return ResourceManager.GetString("TransferScheduleInvalidDate", resourceCulture);
            }
        }
    }
}
