//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCore.Services.Personnel.Core.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCore.Services.Personnel.Core.Localization.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Key] is not valid..
        /// </summary>
        internal static string Config_Key_NotValid {
            get {
                return ResourceManager.GetString("Config_Key_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department Code] cannot be empty..
        /// </summary>
        internal static string Department_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Department_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department] with the same attributes already exists..
        /// </summary>
        internal static string Department_Error_Duplicate {
            get {
                return ResourceManager.GetString("Department_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department] is not valid..
        /// </summary>
        internal static string Department_Error_Empty {
            get {
                return ResourceManager.GetString("Department_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department] is not found..
        /// </summary>
        internal static string Department_Error_NotExists {
            get {
                return ResourceManager.GetString("Department_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department] is not valid..
        /// </summary>
        internal static string Department_Id_Error_Add {
            get {
                return ResourceManager.GetString("Department_Id_Error_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string Department_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("Department_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department Id] cannot be empty..
        /// </summary>
        internal static string Error_Department_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Department_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Department Id] should be empty..
        /// </summary>
        internal static string Error_Department_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Department_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization Id] cannot be empty..
        /// </summary>
        internal static string Error_Organization_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Organization_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization Id] should be empty..
        /// </summary>
        internal static string Error_Organization_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Organization_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel Id] cannot be empty..
        /// </summary>
        internal static string Error_Personnel_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Personnel_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel Id] should be empty..
        /// </summary>
        internal static string Error_Personnel_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Personnel_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account Id] cannot be empty..
        /// </summary>
        internal static string Error_Account_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Account_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account Id] should be empty..
        /// </summary>
        internal static string Error_Account_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Account_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting Id] cannot be empty..
        /// </summary>
        internal static string Error_Setting_Id_Empty {
            get {
                return ResourceManager.GetString("Error_Setting_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting Id] should be empty..
        /// </summary>
        internal static string Error_Setting_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Setting_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization Code] cannot be empty..
        /// </summary>
        internal static string Organization_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Organization_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization] with the same attributes already exists..
        /// </summary>
        internal static string Organization_Error_Duplicate {
            get {
                return ResourceManager.GetString("Organization_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization] is not valid..
        /// </summary>
        internal static string Organization_Error_Empty {
            get {
                return ResourceManager.GetString("Organization_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization] is not found..
        /// </summary>
        internal static string Organization_Error_NotExists {
            get {
                return ResourceManager.GetString("Organization_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization] is not valid..
        /// </summary>
        internal static string Organization_Id_Error_Add {
            get {
                return ResourceManager.GetString("Organization_Id_Error_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Organization Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string Organization_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("Organization_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel Code] cannot be empty..
        /// </summary>
        internal static string Personnel_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Personnel_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel] with the same attributes already exists..
        /// </summary>
        internal static string Personnel_Error_Duplicate {
            get {
                return ResourceManager.GetString("Personnel_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel] is not valid..
        /// </summary>
        internal static string Personnel_Error_Empty {
            get {
                return ResourceManager.GetString("Personnel_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel] is not found..
        /// </summary>
        internal static string Personnel_Error_NotExists {
            get {
                return ResourceManager.GetString("Personnel_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel] is not valid..
        /// </summary>
        internal static string Personnel_Id_Error_Add {
            get {
                return ResourceManager.GetString("Personnel_Id_Error_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Personnel Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string Personnel_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("Personnel_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account Code] cannot be empty..
        /// </summary>
        internal static string Account_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Account_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account] with the same attributes already exists..
        /// </summary>
        internal static string Account_Error_Duplicate {
            get {
                return ResourceManager.GetString("Account_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account] is not valid..
        /// </summary>
        internal static string Account_Error_Empty {
            get {
                return ResourceManager.GetString("Account_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account] is not found..
        /// </summary>
        internal static string Account_Error_NotExists {
            get {
                return ResourceManager.GetString("Account_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account] is not valid..
        /// </summary>
        internal static string Account_Id_Error_Add {
            get {
                return ResourceManager.GetString("Account_Id_Error_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Account Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string Account_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("Account_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting Code] cannot be empty..
        /// </summary>
        internal static string Setting_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Setting_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting] with the same attributes already exists..
        /// </summary>
        internal static string Setting_Error_Duplicate {
            get {
                return ResourceManager.GetString("Setting_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting] is not valid..
        /// </summary>
        internal static string Setting_Error_Empty {
            get {
                return ResourceManager.GetString("Setting_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting] is not found..
        /// </summary>
        internal static string Setting_Error_NotExists {
            get {
                return ResourceManager.GetString("Setting_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting] is not valid..
        /// </summary>
        internal static string Setting_Id_Error_Add {
            get {
                return ResourceManager.GetString("Setting_Id_Error_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Config Setting Id] cannot be zero in edit or delete operation..
        /// </summary>
        internal static string Setting_Id_Error_IsNotEqualZero {
            get {
                return ResourceManager.GetString("Setting_Id_Error_IsNotEqualZero", resourceCulture);
            }
        }
    }
}
