//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCore.Services.Organizations.Core.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCore.Services.Organizations.Core.Localization.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _string {
            get {
                return ResourceManager.GetString("string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [City] is not valid..
        /// </summary>
        internal static string City_Code_Error_Empty1 {
            get {
                return ResourceManager.GetString("City_Code_Error_Empty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [City]with the same attributes already exists..
        /// </summary>
        internal static string City_Error_Duplicate1 {
            get {
                return ResourceManager.GetString("City_Error_Duplicate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [City] is not valid..
        /// </summary>
        internal static string City_Error_Empty1 {
            get {
                return ResourceManager.GetString("City_Error_Empty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [City]  is not found..
        /// </summary>
        internal static string City_Error_NotExists {
            get {
                return ResourceManager.GetString("City_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactInfo Code] cannot be empty..
        /// </summary>
        internal static string ContactInfo_Code_Error_Empty {
            get {
                return ResourceManager.GetString("ContactInfo_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactInfo] with the same attributes already exists..
        /// </summary>
        internal static string ContactInfo_Error_Duplicate {
            get {
                return ResourceManager.GetString("ContactInfo_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactInfo] is not valid..
        /// </summary>
        internal static string ContactInfo_Error_Empty {
            get {
                return ResourceManager.GetString("ContactInfo_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactInfo] is not found..
        /// </summary>
        internal static string ContactInfo_Error_NotExists {
            get {
                return ResourceManager.GetString("ContactInfo_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactPersonal Code] cannot be empty..
        /// </summary>
        internal static string ContactPersonal_Code_Error_Empty {
            get {
                return ResourceManager.GetString("ContactPersonal_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactPersonal] with the same attributes already exists..
        /// </summary>
        internal static string ContactPersonal_Error_Duplicate {
            get {
                return ResourceManager.GetString("ContactPersonal_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactPersonal] is not valid..
        /// </summary>
        internal static string ContactPersonal_Error_Empty {
            get {
                return ResourceManager.GetString("ContactPersonal_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactPersonal] is not found..
        /// </summary>
        internal static string ContactPersonal_Error_NotExists {
            get {
                return ResourceManager.GetString("ContactPersonal_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Department Code] cannot be empty..
        /// </summary>
        internal static string Department_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Department_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Department] with the same attributes already exists..
        /// </summary>
        internal static string Department_Error_Duplicate {
            get {
                return ResourceManager.GetString("Department_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Department] is not valid..
        /// </summary>
        internal static string Department_Error_Empty {
            get {
                return ResourceManager.GetString("Department_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Department] is not found..
        /// </summary>
        internal static string Department_Error_NotExists {
            get {
                return ResourceManager.GetString("Department_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ DepartmentRole] is not valid..
        /// </summary>
        internal static string DepartmentRole_Code_Error_Empty {
            get {
                return ResourceManager.GetString("DepartmentRole_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ DepartmentRole]with the same attributes already exists..
        /// </summary>
        internal static string DepartmentRole_Error_Duplicate {
            get {
                return ResourceManager.GetString("DepartmentRole_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ DepartmentRole] is not valid..
        /// </summary>
        internal static string DepartmentRole_Error_Empty {
            get {
                return ResourceManager.GetString("DepartmentRole_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DepartmentRole]is not found..
        /// </summary>
        internal static string DepartmentRole_Error_NotExists {
            get {
                return ResourceManager.GetString("DepartmentRole_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ City-Id] should be empty..
        /// </summary>
        internal static string Error_City_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_City_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactInfo Id] should not be empty..
        /// </summary>
        internal static string Error_ContactInfo_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_ContactInfo_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ContactPersonal Id] should not be empty..
        /// </summary>
        internal static string Error_ContactPersonal_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_ContactPersonal_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Department Id] should not be empty..
        /// </summary>
        internal static string Error_Department_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Department_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event Id] should be empty..
        /// </summary>
        internal static string Error_Event_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Event_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organization Id] should not be empty..
        /// </summary>
        internal static string Error_Organization_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Organization_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Role Id] should be empty..
        /// </summary>
        internal static string Error_Role_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Role_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Settings Id] should not be empty..
        /// </summary>
        internal static string Error_Settings_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Settings_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ VenueId] should be empty..
        /// </summary>
        internal static string Error_Venue_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Venue_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ VenueDepartmentId] should be empty..
        /// </summary>
        internal static string Error_VenueDepartment_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_VenueDepartment_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ VenueEventId] should be empty..
        /// </summary>
        internal static string Error_VenueEvent_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Error_VenueEvent_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event] is not valid..
        /// </summary>
        internal static string Event_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Event_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event with the same attributes already exists..
        /// </summary>
        internal static string Event_Error_Duplicate {
            get {
                return ResourceManager.GetString("Event_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Event] is not valid..
        /// </summary>
        internal static string Event_Error_Empty {
            get {
                return ResourceManager.GetString("Event_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event] is not found..
        /// </summary>
        internal static string Event_Error_NotExists {
            get {
                return ResourceManager.GetString("Event_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organization Code] cannot be empty..
        /// </summary>
        internal static string Organization_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Organization_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organization] with the same attributes already exists..
        /// </summary>
        internal static string Organization_Error_Duplicate {
            get {
                return ResourceManager.GetString("Organization_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organization] is not valid..
        /// </summary>
        internal static string Organization_Error_Empty {
            get {
                return ResourceManager.GetString("Organization_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Organization] is not found..
        /// </summary>
        internal static string Organization_Error_NotExists {
            get {
                return ResourceManager.GetString("Organization_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Role] is not valid..
        /// </summary>
        internal static string Role_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Role_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Role with the same attributes already exists..
        /// </summary>
        internal static string Role_Error_Duplicate {
            get {
                return ResourceManager.GetString("Role_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Role] is not valid..
        /// </summary>
        internal static string Role_Error_Empty {
            get {
                return ResourceManager.GetString("Role_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Role] is not found..
        /// </summary>
        internal static string Role_Error_NotExists {
            get {
                return ResourceManager.GetString("Role_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Settings Code] cannot be empty..
        /// </summary>
        internal static string Settings_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Settings_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Settings] with the same attributes already exists..
        /// </summary>
        internal static string Settings_Error_Duplicate {
            get {
                return ResourceManager.GetString("Settings_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Settings] is not valid..
        /// </summary>
        internal static string Settings_Error_Empty {
            get {
                return ResourceManager.GetString("Settings_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Settings] is not found..
        /// </summary>
        internal static string Settings_Error_NotExists {
            get {
                return ResourceManager.GetString("Settings_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Venue] is not valid..
        /// </summary>
        internal static string Venue_Code_Error_Empty {
            get {
                return ResourceManager.GetString("Venue_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Venue with the same attributes already exists..
        /// </summary>
        internal static string Venue_Error_Duplicate {
            get {
                return ResourceManager.GetString("Venue_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  Venue] is not valid..
        /// </summary>
        internal static string Venue_Error_Empty {
            get {
                return ResourceManager.GetString("Venue_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Venue ]is not found..
        /// </summary>
        internal static string Venue_Error_NotExists {
            get {
                return ResourceManager.GetString("Venue_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ VenueDepartment] is not valid..
        /// </summary>
        internal static string VenueDepartment_Code_Error_Empty {
            get {
                return ResourceManager.GetString("VenueDepartment_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ VenueDepartment ]with the same attributes already exists..
        /// </summary>
        internal static string VenueDepartment_Error_Duplicate {
            get {
                return ResourceManager.GetString("VenueDepartment_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  VenueDepartment] is not valid..
        /// </summary>
        internal static string VenueDepartment_Error_Empty {
            get {
                return ResourceManager.GetString("VenueDepartment_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VenueEvent] ]is not found..
        /// </summary>
        internal static string VenueDepartment_Error_NotExists {
            get {
                return ResourceManager.GetString("VenueDepartment_Error_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ VenueEvent] is not valid..
        /// </summary>
        internal static string VenueEvent_Code_Error_Empty {
            get {
                return ResourceManager.GetString("VenueEvent_Code_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ VenueEvent ]with the same attributes already exists..
        /// </summary>
        internal static string VenueEvent_Error_Duplicate {
            get {
                return ResourceManager.GetString("VenueEvent_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  VenueEvent] is not valid..
        /// </summary>
        internal static string VenueEvent_Error_Empty {
            get {
                return ResourceManager.GetString("VenueEvent_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VenueEvent ]is not found..
        /// </summary>
        internal static string VenueEvent_Error_NotExists {
            get {
                return ResourceManager.GetString("VenueEvent_Error_NotExists", resourceCulture);
            }
        }
    }
}
